### ISSUE TITLE
Reference resolver not called?

### ISSUE THREAD

**Issue by showenx** [apollographql/subgraph-template-typescript-apollo-server-boilerplate#11]
Hi,
It's a great starter template, I got one question when running it locally with `__resolveReference` 

This `Thing` resolver seems not get called, not sure whether I used it incorrectly
https://github.com/apollographql/subgraph-template-typescript-apollo-server-boilerplate/blob/main/src/resolvers/Thing.ts#L5

**Comment by dbanty** [comment]
The reference resolver is only called when resolving a federated [Entity](https://www.apollographql.com/docs/federation/entities/) which would usually be called by a [Router](https://www.apollographql.com/docs/router), not a manual query. For an example, if we change `__resolveReference` to this, it's easier to see:

```typescript
Thing: {
    __resolveReference(parent, _context) {
      return { id: parent.id, name: "ReferenceName" };
    },
  },
```

Note that in `Query.ts`, we still have this:

```typescript
Query: {
    thing(_parent, { id }, _context) {
      return { id, name: "Name" };
    },
  },
```

If we run a query which fetches both the entity version of `Thing` and the resolver for `Query.thing`, we can see the difference:

```graphql
query Foo($thingId: ID!) {
  _entities(representations: [{__typename: "Thing", id: $thingId}]) {
    ... on Thing {
      name
    }
  }
  thing(id: $thingId) {
    name
  }
}
```

```json
{
  "data": {
    "_entities": [
      {
        "name": "ReferenceName"
      }
    ],
    "thing": {
      "name": "Name"
    }
  }
}
```
Hope that helps!

**Comment by dbanty** [comment]
Here are some more docs on `__resolveReference` specifically: https://www.apollographql.com/docs/apollo-server/using-federation/api/apollo-subgraph/#__resolvereference

**Comment by showenx** [comment]
Hi @dbanty ,
Thanks for hte details, it really helps.

- One further query on the use cases of `__resolveReference`, by looking at the sample code, `thing` could be resolved in `Query -> thing` and `Thing -> __resolveReference`, doses it mean the resolver logic needs to be duplicaated in these two places?

- another question on the use case as  below, with property resolver using the same query

```js
export const Thing: Resolvers = {
  Thing: {
    __resolveReference(parent, _context) {
      return { id: parent.id, name: "ReferenceName" };
    },

    name() {
      return `ad-hoc name`;
    }
  },
};
```

getting the reponse as below:
```json
{
  "data": {
    "_entities": [
      {
        "name": "ad-hoc name"
      }
    ],
    "thing": {
      "name": "ad-hoc name"
    }
  }
}
```
just want to better understand the resolving sequences, based on the testing it seems the property resolver wins

**Comment by dbanty** [comment]
Generally you'd put the resolver logic in one function which is then called from anywhere it's needed (e.g., `Query.thing` and `Thing.__resolveReference`). We're hoping to add data source support (e.g., SQL) to these templates in the near future so we can show more realistic patterns.

As for the resolver-ordering, I'm not sure. I think that'd be a great question to ask [in our Discord](https://discord.gg/graphos) where more people will have answers!
